### ISSUE TITLE
Missing Configuration:

### ISSUE THREAD

**Issue by atazangene** [theogravity/pulumi-fusionauth#13]
Hi
First, Thank you for great job on this package

**application.jwtConfiguration.refreshTokenExpirationPolicy**  is not available inside the fusoinauth-pulumi package

can you check this please
[](https://www.pulumi.com/registry/packages/fusionauth/api-docs/fusionauthapplication/)
[](https://fusionauth.io/docs/v1/tech/apis/applications)

**Comment by theogravity** [comment]
I've built a new bundle using the latest terraform module. Should have it now.
